[Variables]

;;ADOBE;;
Photoshop=["C:\Path\To\App.exe"]

;;Browser;;
Chrome=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
MozillaFirefox=["C:\Path\To\App.exe"]

;;Development;;
Android Studio=["C:\Path\To\App.exe"]
Arduino=["C:\Path\To\App.exe"]
AtlassianSourceTree=["C:\Path\To\App.exe"]
Atom=["C:\Path\To\App.exe"]
CodeBlocks=["C:\Path\To\App.exe"]
Eclipse=["C:\Path\To\App.exe"]
MicrosoftVisualStudio=["C:\Path\To\App.exe"]
MicrosoftVisualStudioCode=["C:\Path\To\App.exe"]
NotepadPlusPlus=["C:\Path\To\App.exe"]
Putty=["C:\Path\To\App.exe"]
ScarDivi=["C:\Path\To\App.exe"]
Winscp=["C:\Path\To\App.exe"]

;;Folders;;
DocumentsFolder=["C:\Users\USERNAME\Documents"]
Downloads=["C:\Users\USERNAME\Downloads"]
FileExplorer=["%SystemRoot%\explorer.exe"]
Games=["C:\Path\To\App.exe"]
GamesFolder=["C:\Path\To\App.exe"]
MoviesFolder=["C:\Path\To\App.exe"]
Pictures=["C:\Users\USERNAME\Pictures"]
Server=["C:\Path\To\App.exe"]
VideosFolder=["C:\Users\USERNAME\Videos"]

;;Game Digital Distribution;;
Battlenet=["C:\Path\To\App.exe"]
Steam=["C:\Path\To\App.exe"]
TechnicLauncher=["C:\Path\To\App.exe"]
TwitchApp=["C:\Path\To\App.exe"]

;;GameEngines;;
GameMakerStudio="steam://rungameid/585410"
RPGMaker=["steam://rungameid/363890"]
Unity=["C:\Path\To\App.exe"]

;;Graphics;;
Aseprite="steam://rungameid/431730"
Blender=["steam://rungameid/365670"]
Fusion360=["C:\Path\To\App.exe"]
Gimp=["C:\Path\To\App.exe"]
Shadron=["C:\Path\To\App.exe"]

;;Media;;
AmazonMusic=["C:\Path\To\App.exe"]
Kodi=["C:\Path\To\App.exe"]
obs=["C:\Path\To\App.exe"]
PopcornTime=["C:\Path\To\App.exe"]
RytmikUltimate="steam://rungameid/375840"
VLCMediaPlayer=["C:\Path\To\App.exe"]

;;MICROSOFT OFFICE;;
Excel=["C:\Path\To\App.exe"]
OneNote=["C:\Path\To\App.exe"]
Word=["C:\Path\To\App.exe"]

;;Others;;
Avast=["C:\Path\To\App.exe"]
Balabolka=["C:\Path\To\App.exe"]
MozillaThunderbird=["C:\Path\To\App.exe"]
TeamViewer=["C:\Path\To\App.exe"]

;;Sites;;
Facebook="https://facebook.com"
GitHub="https://github.com/Kavex?tab=repositories"
GoogleDrive="https://drive.google.com/"
Netflix="http://netflix.com"
;Plex="http://plex.tv"
Plex="http://127.0.0.1:32400/web/index.html" 
Reddit="http://www.reddit.com/"
Twitch="http://www.twitch.tv/"
Youtube="https://www.youtube.com/"

;;System;;
Calculator="calc.exe"]
Computer=["%SystemRoot%\explorer.exe"]
ControlPanel=[%SystemRoot%\system32\control.exe]
RecycleBin=!execute [!RainmeterPluginBang "MeasureBinSize OpenBin"]
;RecycleBin=["C:\Dropbox\Data\Shortcuts\Uninstall_Programs"] ;Uncomment this for "Uninstall programs"
Search=["#CURRENTPATH#Search.exe"]
Terminal=["cmd"]

;;Torrent;;
Transmission=["C:\Path\To\App.exe"]

;;Voice;;
Discord=["C:\Path\To\App.exe"]
Mumble=["C:\Path\To\App.exe"]
Skype=["C:\Path\To\App.exe"]
Teamspeak=["C:\Path\To\App.exe"]

;;VPN;;
Evolve=["C:\Path\To\App.exe"]


