[Variables]

;;ADOBE;;
AfterEffects=["C:\Path\To\App.exe"]
Audition=["C:\Path\To\App.exe"]
Bridge=["C:\Path\To\App.exe"]
Dreamweaver=["C:\Path\To\App.exe"]
Encore=["C:\Path\To\App.exe"]
Fireworks=["C:\Path\To\App.exe"]
FlashBuilder=["C:\Path\To\App.exe"]
FlashPro=["C:\Path\To\App.exe"]
Illustrator=["C:\Path\To\App.exe"]
InDesign=["C:\Path\To\App.exe"]
Lightroom=["C:\Path\To\App.exe"]
Photoshop=["C:\Path\To\App.exe"]
Prelude=["C:\Path\To\App.exe"]
PremirePro=[""]
SpeedGrade=["C:\Path\To\App.exe"]

;;Anti-Virus;;
Avast=["C:\Path\To\App.exe"]
AVG=["C:\Path\To\App.exe"]

;;Browser;;
Chrome=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
MozillaFirefox=["C:\Path\To\App.exe"]
Opera=["C:\Path\To\App.exe"]

;;Development;;
Android Studio=["C:\Path\To\App.exe"]
Arduino=["C:\Program Files (x86)\Arduino\arduino.exe"]
AtlassianSourceTree=["C:\Program Files (x86)\Atlassian\SourceTree\SourceTree.exe"]
Atom=["C:\Path\To\App.exe"]
CodeBlocks=["C:\Path\To\App.exe"]
Eclipse=["C:\Path\To\App.exe"]
MicrosoftVisualStudio=["C:\Path\To\App.exe"]
MicrosoftVisualStudioCode=["C:\Path\To\App.exe"]
NotepadPlusPlus=["C:\Program Files (x86)\Notepad++\notpad++.exe"]
Putty=["C:\Program Files (x86)\PuTTY\putty.exe"]
ScarDivi=["C:\Program Files (x86)\SCAR Divi\bin\scar.exe"]
SublimeText=["C:\Path\To\App.exe"]
Winscp=["C:\Program Files (x86)\WinSCP\WinSCP.exe"]

;;Folders;;
DocumentsFolder=["C:\Users\USERNAME\Documents"]
Downloads=["C:\Users\USERNAME\Downloads"]
FileExplorer=["%SystemRoot%\explorer.exe"]
Games=["C:\Path\To\App.exe"]
GamesFolder=["C:\Path\To\App.exe"]
MoviesFolder=["C:\Path\To\App.exe"]
Pictures=["C:\Users\USERNAME\Pictures"]
Server=["C:\Path\To\App.exe"]
VideosFolder=["C:\Users\USERNAME\Videos"]

;;Game Digital Distribution;;
Curse=["C:\Users\USERNAME\AppData\Roaming\Curse Client\Bin\Curse.exe"]
GOG=["C:\Path\To\App.exe"]
Origin=["C:\Path\To\App.exe"]
Steam=["C:\Program Files (x86)\Steam\Steam.exe"]
UPlay=["C:\Path\To\App.exe"]

;;GameEngines;;
GameMakerStudio"steam://rungameid/214850"
Godot=["C:\Path\To\App.exe"]
RPGMaker=["C:\Path\To\App.exe"]
Unity=["C:\Program Files\Unity\Editor\Unity.exe"]

;;Games;;
ArcheAge="steam://rungameid/304030"
;Arma="steam://rungameid/107410"
Arma="C:\Games\Arma3\arma3.exe"
Battlenet=["C:\Program Files (x86)\Battle.net\Battle.net Launcher.exe"]
BattleBlockTheater="steam://rungameid/238460"
BattlefieldFour=["C:\Program Files (x86)\Origin Games\Battlefield 4\bf4"]
BattlefieldHardline=["C:\Path\To\App.exe"]
Blade=["C:\Path\To\App.exe"]
CallofDutyAdvancedWarfare=["steam://rungameid/209650"]
CallofDutyBlackOpsMultiplayer=["steam://rungameid/202990"]
CallofDutyBlackOpsSingleplayer=["steam://rungameid/202970"]
CallofDutyBlackOpsZombies=["steam://rungameid/212910"]
CallofDutyWaW=["steam://rungameid/10090"]
CitiesSkylines="steam://rungameid/255710"
CSGO="steam://rungameid/730"
Diablo3=["C:\Program Files (x86)\Diablo III\Diablo III Launcher.exe"]
Dirt=["C:\Path\To\App.exe"]
Dolphin=["C:\Path\To\App.exe"]
Doom="steam://rungameid/379720"
Dota=["C:\Path\To\App.exe"]
Fallout=["steam://rungameid/377160"]
EuropaUniversalisIV=["steam://rungameid/236850"]
FinalFantasy=["steam://rungameid/39210"]
Garry=["steam://rungameid/4000"]
GTAV=["steam://rungameid/271590"]
HalfLife=["steam://rungameid/70"]
Hearthstone=["C:\Program Files (x86)\Hearthstone\Hearthstone Beta Launcher.exe"]
LeagueofLegends=["C:\Riot Games\League of Legends\lol.launcher.exe"]
LethalLeague=["C:\Games\Lethal League\Lethal League LanGame.exe"]
;LoLNexus="http://www.lolnexus.com/"
LoLNexus="C:\Dropbox\Data\Shortcuts\LoLNexus"
Marvel=["C:\Path\To\App.exe"]
Minecraft=["C:\Path\To\App.exe"]
Monaco=["C:\Path\To\App.exe"]
Neverwinter=["C:\Path\To\App.exe"]
osu!=["C:\Path\To\App.exe"]
Overwatch=["C:\Path\To\App.exe"]
payday_2=["steam://rungameid/218620"]
Portal=["steam://rungameid/620"]
QuakeLive=["C:\Path\To\App.exe"]
RainbowSixVegas=["steam://rungameid/15120"]
RocketLeague="steam://rungameid/252950"
Runescape=["C:\Path\To\App.exe"]
Skyrim=["steam://rungameid/72850"]
Speedrunners=["steam://rungameid/207140"]
Squad=["C:\Path\To\App.exe"]
StardewValley="steam://rungameid/413150"
TeamFortress=["steam://rungameid/440"]
TechnicLauncher=["C:\Path\To\App.exe"]
Terraria=["steam://rungameid/105600"]
TheForest="steam://rungameid/242760"
Undertale="steam://rungameid/391540"
WatchDogs=["steam://rungameid/243470"]
Witcher=["steam://rungameid/292030"]
WorldofTanks=["C:\Path\To\App.exe"]
WoW=["C:\Path\To\App.exe"]

;;Graphics;;
Aseprite="steam://rungameid/431730"
Blender=["steam://rungameid/365670"]
CinemaFourD=["C:\Path\To\App.exe"]
Crazybump=["C:\Path\To\App.exe"]
Fusion360=["C:\Path\To\App.exe"]
Gimp=["C:\Program Files\GIMP 2\bin\gimp-2.8.exe"]
Krita=["C:\Program Files\Krita (x64)\bin\krita.exe"]
Shadron=["C:\Path\To\App.exe"]

;;Media;;
AbletonLive=["C:\Path\To\App.exe"]
AmazonMusic=["C:\Path\To\App.exe"]
Audacity=["C:\Path\To\App.exe"]
FLStudio=["C:\Path\To\App.exe"]
iTunes=["C:\Path\To\App.exe"]
Kodi=["C:\Program Files (x86)\Kodi\Kodi.exe"]
MusicBee=["C:\Path\To\App.exe"]
PopcornTime=["C:\Program Files (x86)\Popcorn Time\PopcornTimeDesktop.exe"]
RytmikUltimate=["steam://rungameid/375840"]
Spotify=["C:\Users\USERNAME\AppData\Roaming\Spotify"]
VLCMediaPlayer=["C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"]
Winamp=["C:\Path\To\App.exe"]
WindowsMediaPlayer=["%ProgramFiles(x86)%\Windows Media Player\wmplayer.exe"]
XBMC=["C:\Path\To\App.exe"]

;;MICROSOFT OFFICE;;
Access=["C:\Path\To\App.exe"]
Excel=["C:\Path\To\App.exe"]
infoPath=["C:\Path\To\App.exe"]
Lync=["C:\Path\To\App.exe"]
Office=["C:\Path\To\App.exe"]
OneNote=["C:\Path\To\App.exe"]
Outlook=["C:\Path\To\App.exe"]
PowerPoint=["C:\Path\To\App.exe"]
Project=["C:\Path\To\App.exe"]
Publisher=["C:\Path\To\App.exe"]
Visio=["C:\Path\To\App.exe"]
Word=["C:\Path\To\App.exe"]

;;Others;;
Balabolka=["C:\Program Files (x86)\Balabolka\balabolka.exe"]
CCleaner=["C:\Path\To\App.exe"]
Dashlane=["C:\Path\To\App.exe"]
Deluge=["C:\Path\To\App.exe"]
Dropbox=["C:\Path\To\App.exe"]
Fraps=["C:\Path\To\App.exe"]
GeForceExperience=["C:\Path\To\App.exe"]
MadCatz=["C:\Path\To\App.exe"]
MozillaThunderbird=["C:\Program Files (x86)\Mozilla Thunderbird\thunderbird.exe"]
MSIAfterburner=["C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe"]
obs=["C:\Program Files (x86)\OBS\OBS.exe"]
Onedrive=["C:\Path\To\App.exe"]
OneFingerDeathPunch=["C:\Path\To\App.exe"]
SonyVegas=["C:\Path\To\App.exe"]
TeamViewer=["C:\Program Files (x86)\TeamViewer\TeamViewer.exe"]
XSplit=["C:\Program Files (x86)\SplitmediaLabs\XSplit Broadcaster\XSplit.Core.exe"]

;;Sites;;
Facebook="https://facebook.com"
FieldNation="https://fieldnation.com"
GitHub="https://github.com"
Gmail="https://mail.google.com"
GoogleDrive="https://drive.google.com/"
Netflix="http://netflix.com"
Plex="http://plex.tv"
;Plex="http://localhost:32400/web/index.html" 
Reddit="http://www.reddit.com/"
Soundcloud="https://soundcloud.com"
Twitch="http://www.twitch.tv/"
Twitter="https://twitter.com"
Youtube="https://www.youtube.com/"

;;System;;
Calculator="calc.exe"]
Computer=["%SystemRoot%\explorer.exe"]
ControlPanel=[%SystemRoot%\system32\control.exe]
RecycleBin=!execute [!RainmeterPluginBang "MeasureBinSize OpenBin"]
;RecycleBin=["C:\Dropbox\Data\Shortcuts\Uninstall_Programs"] ;Uncomment this for "Uninstall programs"
Search=["#CURRENTPATH#Search.exe"]
Terminal=["cmd"]

;;Torrent;;
Bittorrent=["C:\Path\To\App.exe"]
AAuTorrent=["C:\Users\Karl\AppData\Roaming\uTorrent\uTorrent.exe"]
Transmission=[""C:\Program Files\Transmission\transmission-qt.exe""]
uTorrent=["%APPDATA%\uTorrent\uTorrent.exe"]

;;Voice;;
Discord=["C:\Path\To\App.exe"]
Mumble=["C:\Program Files (x86)\Mumble\mumble.exe"]
Skype=["C:\Program Files (x86)\Skype\Phone\Skype.exe"]
Teamspeak=["C:\Path\To\App.exe"]

;;VPN;;
Evolve=["C:\Path\To\App.exe"]
Hamachi=["C:\Program Files (x86)\LogMeIn Hamachi\hamachi-2-ui.exe"]
Tunngle=["C:\Program Files (x86)\Tunngle\Tunngle.exe"]